tag-prefix: ""
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📚 Documentation'
    label: 'documentation'
  - title: '🔒 Security'
    label: 'security'
  - title: '🧰 GitHub Actions'
    label: 'github actions'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

change-title-escapes: '\<*_&"'''
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/[A-Z]+-[0-9]+/'
  - label: 'documentation'
    files:
      - '**/*.md'
      - 'docs/**/*'
  - label: 'security'
    branch:
      - '/security\/.+/'

include-labels:
  - 'documentation'
  - 'bug'
  - 'enhancement'
  - 'security'
  - 'github actions'

replacers:
  - search: /"/g
    replace: ''
  - search: /'/g
    replace: ''
  - search: /`/g
    replace: ''
exclude-labels:
  - 'skip-changelog'

filter-by-commitish: false