name = "System Setup"

[[data]]
name = "Full System Update"
script = "system-update.sh"

[[data]]
name = "Build Prerequisites"
script = "1-compile-setup.sh"

[[data]]
name = "Gaming Dependencies"
script = "2-gaming-setup.sh"

[[data]]
name = "Global Theme"
script = "3-global-theme.sh"

[[data]]
name = "Remove Snaps"
script = "4-remove-snaps.sh"
