name: ShellCheck

on:
  pull_request:
    paths:
      - 'tabs/**/*.sh'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: 'tabs'
        severity: error